### ISSUE TITLE
crawling  from several website

### ISSUE THREAD

**Issue by pramirhossein** [mehmetozkaya/DotnetCrawler#2]
Hi ,

I wana crawling from several wensite . The problem is that my entity is only capable  receiving information from a site . Is there a solution to this dynamic?

**Comment by mehmetozkaya** [comment]
Hi,
The current codes support to one Entity mapping, but it could be extend.
In your case, I am just thinking that you should convert a list type to Expression property of DotnetCrawlerFieldAttribute.cs as below way;
Hide   Copy Code
public class DotnetCrawlerFieldAttribute : Attribute
   {
       public List<string> Expression { get; set; }
       public SelectorType SelectorType { get; set; }
   }

After that ReflectionHelper.GetPropertyAttributes method return type should be updated as a List<string> value of attribute in order to get list of expressions.
Hide   Copy Code
public static Dictionary<string, Tuple<SelectorType, List<string>>> GetPropertyAttributes<TEntity>()

After that DotnetCrawlerProcessor.GetColumnNameValuePairsFromHtml() method could be update accordingly. And also DotnetCrawlerRequest.Url property should take list of urls.

So that means it could be convert to take more than one resource and process but it takes to change lots of place.
So another approach could be using DotnetCrawler.exe with asynchronous way. That means you can run crawler in paralel tasks, in example, if you dont use wait command as below code block, you can call crawler at the same time with different methods and both of them crawl different urls.
Hide   Copy Code
static void Main(string[] args)
        {
            MainAsync(args).Wait();
        }

**Comment by pramirhossein** [comment]
Thanks for your help
